name: Report Hub CI

on:
  push:
    branches: [ '*' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r requirements-test.txt

    - name: Run tests with PyTest
      run: |
        pytest --disable-warnings --cov

    - name: Upload coverage to GitHub
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: .coverage

    - name: Build the Docker image
      run: docker build . -f Dockerfile -t report-hub

    - name: Push the Docker image
      if: success()
      run: |
        docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
        docker tag report-hub ghcr.io/${{ github.repository }}/report-hub:latest
        docker tag report-hub ghcr.io/${{ github.repository }}/report-hub:${{ github.run_number}}.${{ github.run_id}}
        docker push ghcr.io/${{ github.repository }}/report-hub:latest
        docker push ghcr.io/${{ github.repository }}/report-hub:${{ github.run_number}}.${{ github.run_id}}
